### ISSUE TITLE
화면에 보이지만 눌리지 않는 UI  

### ISSUE THREAD

**Issue by ellen8880** [uprise-fin/iruda-project#12]
### 테스트 환경

- 기종: Redmi note 6 Pro
- UI: MIUI Global 12.0.1
- Android Version: 9 PKQ1.180904.001

### 사전조건

- 회원가입 → 본인인증 단계에서 화면에서 다 보이지만 눌리지 않는 UI가 있음 (Redmi Note 6 Pro)

### 재현과정

![image.png](https://images.zenhubusercontent.com/5e5d02d4560053871e6b5c2e/48dcad32-f913-47db-ac9a-1f9f45754506)!

- 재현 조건
    - 본인인증 화면에 들어왔을 때 스크롤하지 않아도 주민등록번호 입력창이 보이지만 탭해서 활성화 할 수 없음
    - 스크롤을 20px 정도 위로 올리면 탭 가능
    - 사진은 탭 할 수 없는 상태

![image.png](https://images.zenhubusercontent.com/5e5d02d4560053871e6b5c2e/ec6ac6d0-3608-456d-9a4f-83925bc1283c)

- 재현 조건
    - 휴대전화 번호 인증 요청 버튼도 스크롤 할 수 있는 최대치까지 위로 올려야 탭 가능
    - 사진은 탭 할 수 있을 정도로 스크롤한 상태

### 이슈사항

- 화면에 UI가 다 보이지만 뭔가에 막혀서 탭할 수 없는 상태가 되고 기대한 것 보다 더 위쪽으로 스크롤하면 탭 가능

### 기대결과

- 화면에 UI가 다 보인다면 탭 되는 것이 사용자가 기대하는 동작 방식

**Comment by ellen8880** [comment]
해당 건 테스트 기기 중 갤럭시노트에서 확인 가능
placeholder 터치 시엔 액션이 없고, 
그 옆 빈 공간 터치, 또는 스크롤 했을 시 입력 가능
---
하단에 버튼이 존재하고 그 위 영역이 터치되지 않는 것으로 보아, 
기존에 등록된 버튼이 눌리지 않는 건과 다른 것으로 보여짐 ( [해당 건 보기](https://www.notion.so/upriseinc/CS-0f5d89b42fc64826a0ae4d55269eee32) )

by 리암

**Comment by liamkim88** [comment]
- 해당 건 dev 환경, 재현되었던 기기 갤럭시노트에서 수정 확인되었습니다. 
- 아이폰 SE2, 아이폰 12 미니, 갤럭시 S21, 아이폰 11 프로 에서도 추가 확인되었습니다. 

https://images.zenhubusercontent.com/440398403/bc9d7fbe-3f22-4c78-898d-289b3e61097b/screen_recording_20220114_093509__dev_debug.mp4

**Comment by liamkim88** [comment]
해당 건 상용 적용되어 close 처리 하겠습니다.
