### ISSUE TITLE
[기능요청] dev Admin에만 유저 강제 탈퇴 기능 추가

### ISSUE THREAD

**Issue by liamkim88** [uprise-fin/iruda-project#49]
### 요청개요
- 투자 해지 진행 중 단계가 추가되면서, 테스트 계정의 탈퇴가 어려워짐
- 1회용 메일로 가입은 계속 진행할 수는 있으나, 탈퇴가 되지 않기 때문에 계정 관리의 어려움

### 기능
- Dev Admin에만 [테스트계좌생성] 기능 생성처럼 유저를 강제 해지, 탈퇴 시키는 기능 추가 및 노출
- 상용 Admin에서는 미노출 처리

### 참고사항
- 우선순위가 아주 높은 기능은 아닙니다. 
- denny께는 구두로 설명 드렸습니다.

**Comment by liamkim88** [comment]
dev Admin에서 탈퇴 기능 동작 확인되었습니다. 
@Forrest-heybit  빠른 대응 감사드립니다~

**Comment by Forrest-heybit** [comment]
@liamkim88 테그 달지 마세요.. ㅠㅠ 데니가 알아서 해주신거에요.
이런 카드 있는지도 몰랐어요 >_<;;;;

**Comment by liamkim88** [comment]
어라? denny 태그 달았는데 포레스트가 걸렸네요 ㅠ
